site_name: PlayTest Buddy Documentation
site_description: Mobil uygulama test süreçlerini kolaylaştıran topluluk destekli platform.
site_url: https://ismailaricioglu.github.io/PlayTest-Buddy/
repo_url: https://github.com/ismailaricioglu/PlayTest-Buddy
repo_name: PlayTestBuddy

theme:
  name: material
  language: tr
  features:
    - navigation.tabs
    - navigation.instant
    - search.suggest
    - content.code.copy

nav:
  - Anasayfa: index.md
  - Gereksinimler:
      - İş Gereksinimi: System_Requirements.md
      - Sistem Gereksinimi: System_Requirements.md
  - Tasarım:
      - Fonksiyonel Tasarım: Functional_Design.md
      - Alt Sistem Tasarımı: SubSystem_Design.md
      - Detay Tasarım: Detailed_Design.md
  - Test Dokümantasyonu:
      - Test Tasarımı ve RTM: Test_Design_RTM.md
      - Kabul Test Planı: Acceptance_Test_Plan.md
      - Kabul Test Raporu: Acceptance_Test_Report.md
  - Rehberler:
      - Geliştirici Rehberi: guides/Developer_Guide_PlayTestBuddy.md
      - Kullanıcı Rehberi: guides/User_Guide_PlayTestBuddy.md
      - Yönetici Rehberi: guides/Admin_Guide_PlayTestBuddy.md
  - Topluluk:
      - Katkı Rehberi: ../CONTRIBUTING.md
      - Topluluk Rehberi: guides/Community_Guide_PlayTestBuddy.md
      - Lisans: ../LICENSE

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      guess_lang: false
  - tables
  - footnotes
